name:                fuzzyset
version:             0.1.2
synopsis:            Fuzzy set for approximate string matching
description:         This library is based on the Python and JavaScript libraries with similar names.
homepage:            https://github.com/laserpants/fuzzyset-haskell
license:             BSD3
license-file:        LICENSE
author:              Johannes Hildén
maintainer:          hildenjohannes@gmail.com
copyright:           2019 Johannes Hildén
category:            Data
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - unordered-containers >= 0.2.10.0 && < 0.3
  - vector >= 0.12.0.3 && < 0.13
  - text >= 1.2.3.1 && < 1.3
  - text-metrics >= 0.3.0 && < 0.4
  - data-default >= 0.7.1.1 && < 0.8

library:
  source-dirs: src

executables:
  fuzzyset-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuzzyset

tests:
  fuzzyset-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuzzyset
    - hspec >= 2.7.1 && < 2.8
    - ieee754 >= 0.8.0 && < 0.9
