name:                fuzzyset
version:             0.3.0
synopsis:            Fuzzy set data structure for approximate string matching
github:              laserpants/fuzzyset-haskell
license:             BSD-3-Clause
license-file:        LICENSE
author:              "Heikki Johannes Hildén"
maintainer:          "hildenjohannes@gmail.com"
copyright:           2017-present laserpants
category:            Data

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/laserpants/fuzzyset-haskell#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  fuzzyset-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fuzzyset
